---
- name: Create mysql for WordPress
  hosts: servers
  become: yes
  become_user: root
  
  tasks: 
    - name: Install required packages
      apt:
        name:
         # - nginx
          #- mysql-server
          - php-fpm
          - php-mysql
          - php-cli
          - php-curl
          - php-gd
          - php-mbstring
          - unzip

    - name: Start and enable services
      systemd:
        name: "{{item}}"
        enabled: yes
        state: started
      with_items:
        - nginx
        - mysql

    - name: Include MySQL credentials
      include_vars: mysql_credentials.yml

    - name: creating mysql user
      mysql_user:
        name: "{{mysql_db_user}}"
        password: "{{mysql_db_password}}"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: creating mysql_db
      mysql_db:
        name: "{{mysql_db_name}}"
        state: present    
        