---
- hosts: servers
  become: yes
  become_user: root

  tasks:
    - name: Include MySQL credentials
      include_vars: mysql_credentials.yml
      vars_files:
        - path/to/encrypted/mysql_credentials.yml
      vars_prompt:
        - name: "vault_password"
          prompt: "Enter Ansible Vault Password"
          private: yes
      no_log: "{{ vault_password }}"


    - name: Log in as MySQL root user
      mysql_login:
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user
      mysql_user:
        name: "{{ mysql_new_user }}"
        host: "{{ mysql_host }}"
        password: "{{ mysql_new_user_password }}"
        priv: "*.*:ALL"

    - name: Log out from MySQL root user
      mysql_login:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: logout

    - name: Log in as the new MySQL user
      mysql_login:
        login_user: "{{ mysql_new_user }}"
        login_password: "{{ mysql_new_user_password }}"
        login_host: "{{ mysql_host }}"



    - name: Secure MySQL installation
      mysql_user:
        login_user: root
        login_password: "{{mysql_root_password}}"
        user: root
        password: "{{mysql_root_password}}"
        host: localhost
        priv: "*.*:ALL"

    - name: Create MySQL database for WordPress
      mysql_db:
        name: "{{mysql_db_name}}"
        state: present
        login_user: root
        login_password: "{{mysql_root_password}}"

    - name: Create MySQL user for WordPress
      mysql_user:
        name: "{{mysql_db_user}}"
        password: "{{mysql_db_password}}"
        priv: "{{mysql_db_name}}.*:ALL"
        state: present
        login_user: root
        login_password: "{{mysql_root_password}}"